apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: student-pvc
spec:
  storageClassName: ""            # opt out of the default class -> bind to a pre-created PV
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
